name = "wod-push"
main = "src/index.js"
compatibility_date = "2025-10-29"

[[kv_namespaces]]
binding = "WOD_SUBS"
id = "b451e3ce14574addac61f6032a6f97dd"

[[kv_namespaces]]
binding = "WOD_META"
id = "0209cc04fcd44a338d2d67a45c471e30"

[triggers]
# 8:00 AM PT across DST: 15:00 UTC (PDT) and 16:00 UTC (PST)
crons = ["0 15 * * *", "0 16 * * *"]
